apiVersion: batch/v1
kind: CronJob
metadata:
  name: your-dbt-project
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dbt-jaffle-shop
            image: elisska/dbt-jaffle-shop
            env:
              - name: HIVE_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: dbt-spark
                    key: hive-schema
              - name: THRIFT_SERVER_HOST
                valueFrom:
                  configMapKeyRef:
                    name: dbt-spark
                    key: thrift-server-host
              - name: THRIFT_SERVER_PORT
                valueFrom:
                  configMapKeyRef:
                    name: dbt-spark
                    key: thrift-server-port
            imagePullPolicy: Always
          restartPolicy: OnFailure
