apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yml
- cronjob.yml
namespace: dbt
images:
- name: dbt-jaffle-shop
  newName: elisska/dbt-jaffle-shop
  newTag: latest
