version: "3.9"
services:
  dbt_pipeline:
    image: elisska/dbt-jaffle-shop:latest
    ports:
      - "8080:8080"
    environment:
      - HIVE_DATABASE=${HIVE_DATABASE}
      - THRIFT_SERVER_HOST=${THRIFT_SERVER_HOST}
      - THRIFT_SERVER_PORT=${THRIFT_SERVER_PORT}
