jaffle_shop_postgres:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('SCHEMA_NAME') }}"
  target: dev

jaffle_shop_spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: "{{ env_var('HIVE_DATABASE') }}"
      host: "{{ env_var('THRIFT_SERVER_HOST') }}"
      port: "{{ env_var('THRIFT_SERVER_PORT') | as_number }}"
